CRITICAL - 2021-05-21 16:10:24 --> Call to a member function getRandomName() on null
#0 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\Documento->guardar()
#1 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Documento))
#2 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-05-21 16:10:24 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\apica\app\Config\Events.php:35) in C:\xampp\htdocs\apica\system\Debug\Exceptions.php:137
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 137)
#1 C:\xampp\htdocs\apica\system\Debug\Exceptions.php(137): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-05-21 16:11:50 --> Call to a member function getRandomName() on null
#0 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\Documento->guardar()
#1 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Documento))
#2 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-05-21 16:11:50 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\apica\app\Config\Events.php:35) in C:\xampp\htdocs\apica\system\Debug\Exceptions.php:137
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 137)
#1 C:\xampp\htdocs\apica\system\Debug\Exceptions.php(137): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-05-21 16:13:31 --> Call to a member function getRandomName() on null
#0 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\Documento->guardar()
#1 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Documento))
#2 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-05-21 16:13:31 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\apica\app\Config\Events.php:35) in C:\xampp\htdocs\apica\system\Debug\Exceptions.php:137
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 137)
#1 C:\xampp\htdocs\apica\system\Debug\Exceptions.php(137): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-05-21 16:14:32 --> Call to a member function getRandomName() on null
#0 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\Documento->guardar()
#1 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Documento))
#2 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-05-21 16:14:32 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\apica\app\Config\Events.php:35) in C:\xampp\htdocs\apica\system\Debug\Exceptions.php:137
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 137)
#1 C:\xampp\htdocs\apica\system\Debug\Exceptions.php(137): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-05-21 16:14:48 --> Call to a member function getRandomName() on null
#0 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\Documento->guardar()
#1 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Documento))
#2 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-05-21 16:14:48 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\apica\app\Config\Events.php:35) in C:\xampp\htdocs\apica\system\Debug\Exceptions.php:137
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 137)
#1 C:\xampp\htdocs\apica\system\Debug\Exceptions.php(137): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
